# Generated by Django 3.0.2 on 2020-01-17 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0002_auto_20200117_2326'),
        ('event', '0002_event_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('length', models.DurationField()),
                ('complexity', models.SmallIntegerField()),
                ('min_players', models.SmallIntegerField()),
                ('max_players', models.SmallIntegerField()),
                ('image_url', models.URLField(max_length=4000)),
                ('bgg_id', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('players', models.ManyToManyField(to='player.Player')),
            ],
        ),
    ]
