# Generated by Django 3.0.2 on 2020-01-17 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='bgg_id',
        ),
        migrations.RemoveField(
            model_name='play',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='play',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='play',
            name='length',
        ),
        migrations.RemoveField(
            model_name='play',
            name='max_players',
        ),
        migrations.RemoveField(
            model_name='play',
            name='min_players',
        ),
        migrations.RemoveField(
            model_name='play',
            name='name',
        ),
    ]
