# Generated by Django 3.0.2 on 2020-01-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_auto_20200118_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
