# Generated by Django 3.0.2 on 2020-01-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_play_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='score',
            field=models.FloatField(help_text='The score received per-winner for this play.'),
        ),
    ]
