# Generated by Django 3.0.2 on 2020-01-19 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_auto_20200119_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='score',
        ),
    ]
