version: "3.7"

services:
  nginx:
    image: linuxserver/letsencrypt
    cap_add:
      - NET_ADMIN
    env_file:
      .env
    volumes:
      - ./nginx:/config
      - media:/media
    ports:
      - 80:80
      - 443:443
    restart: always

volumes:
  media:
