version: "3.7"

services:
  app:
    image: app:latest
    entrypoint:
      - sh
      - entrypoint.sh
    build:
      context: ./tournament
      dockerfile: ./Dockerfile
    volumes:
      - ./tournament:/app
      - static:/static
      - media:/media
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
  postgres:
    image: postgres:latest
    volumes:
      - database:/var/lib/postgresql/data/
    restart: always
  redis:
    image: redis:latest
    restart: always

volumes:
  database:
  static:
  media:
