version: "3.8"

services:
  app:
    entrypoint:
      - sh
      - entrypoint.production.sh
  nginx:
    image: linuxserver/letsencrypt
    cap_add:
      - NET_ADMIN
    env_file:
      .env
    volumes:
      - ./nginx:/config
      - static:/static
      - media:/media
    ports:
      - 80:80
      - 443:443
    restart: always

volumes:
  static:
  media:
