# Generated by Django 3.0.2 on 2020-01-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('length', models.DurationField()),
                ('complexity', models.SmallIntegerField()),
                ('min_players', models.SmallIntegerField()),
                ('max_players', models.SmallIntegerField()),
                ('image_url', models.URLField()),
                ('bgg_id', models.IntegerField()),
            ],
        ),
    ]
