# Generated by Django 3.0.2 on 2020-01-30 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bgg_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('game_type', models.CharField(blank=True, choices=[('boardgame', 'Board Game'), ('videogame', 'Video Game')], max_length=100)),
                ('min_age', models.SmallIntegerField(blank=True)),
                ('min_length', models.DurationField(blank=True)),
                ('max_length', models.DurationField(blank=True)),
                ('complexity', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('min_players', models.SmallIntegerField(blank=True)),
                ('max_players', models.SmallIntegerField(blank=True)),
                ('url', models.URLField(blank=True, max_length=4000)),
                ('image_url', models.URLField(blank=True, max_length=4000)),
            ],
        ),
    ]
