# Generated by Django 3.0.2 on 2020-01-18 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200118_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_length',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_length',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
