# Generated by Django 3.0.2 on 2020-01-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200118_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='complexity',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
