# Generated by Django 3.0.2 on 2020-01-18 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200118_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='game',
            name='complexity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_length',
            field=models.DurationField(blank=True, default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_length',
            field=models.DurationField(blank=True, default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_players',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
