# Generated by Django 3.0.2 on 2020-01-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200118_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(blank=True, choices=[('boardgame', 'Board Game'), ('videogame', 'Video Game')], max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='min_age',
            field=models.SmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
