# Generated by Django 3.0.2 on 2020-01-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200118_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_length',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_length',
            field=models.DurationField(blank=True),
        ),
    ]
