# Generated by Django 3.0.2 on 2020-01-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200118_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bgg_id',
            field=models.IntegerField(blank=True),
        ),
    ]
