# Generated by Django 3.0.2 on 2020-01-30 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('players', models.ManyToManyField(to='player.Player')),
            ],
        ),
    ]
