# Generated by Django 3.0.2 on 2020-01-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(to='player.Player'),
        ),
    ]
