# Generated by Django 3.0.2 on 2020-05-09 20:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('url', models.URLField(max_length=8192)),
                ('request_type', models.CharField(choices=[('POST', 'POST')], default='POST', max_length=10)),
                ('content_type', models.CharField(default='application/json', max_length=1024)),
                ('content', models.CharField(blank=True, help_text='POST body content. Play data can be interpolated with: %%play_summary%%', max_length=8192, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
    ]
