# Generated by Django 3.0.2 on 2020-01-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200120_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
