# Generated by Django 3.0.2 on 2020-05-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='content',
            field=models.TextField(blank=True, help_text='POST body content. Play data can be interpolated with: %%play_summary%%', null=True),
        ),
    ]
